server:
  port: 8771
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**,/test/**
        
      - id: contact-service
        uri: lb://contact-service
        predicates:
        - Path=/contact/**
        
        